spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: 136794703@qq.com
    password: esxvumnkqacybibh
    properties:
      from: 136794703@qq.com
      mail:
        smtp:
          ssl:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/springdemo?useUnicode=true&characterEncoding=utf-8&charset=utf8mb4&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 121.40.224.146
      port: 6379
      database: 0

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.ming.mapper: debug
